memo/urls.py
from django.urls import path, include
from . import views

app_name = 'memo'
urlpatterns = [
    path('', views.MemoLV.as_view() ,name='index'),
    path('join/', views.signup, name='join'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('make/', views.make, name='make'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('modify/<int:pk>/', views.modify, name='modify'),
    path('like/<int:pk>/', views.like, name='like'),
]

project_memo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('memo.urls'))
]

memo/models.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models import User

# Create your models here.
class Memo(models.Model):
    user_name = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    likes = models.ManyToManyField(User, related_name='likes', blank=True)
    update_time = models.DateTimeField(default=now)

    def __str__(self):
        return self.title

    def save_memo(self):
        self.save()

    def total_like(self):
        return self.likes.count()

memo/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView

from .models import Memo
from django.http import HttpResponseRedirect
from .foms import UserForm, LoginForm, MemoForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.db.models import Count

# Create your views here.

class MemoLV(ListView):
    model = Memo
    queryset = Memo.objects.all()

    def get(self, request, *args, **kwargs):
        orderby = request.GET.get('orderby')

        if orderby == 'like':
            self.queryset = Memo.objects.annotate(like_count=Count('likes')).order_by('-like_count', '-update_time')
        elif orderby == 'mypost':
            if User.is_authenticated:
                user = User.objects.get(username=request.user.get_username())
                self.queryset = Memo.objects.filter(user_name=user)
            else:
                self.queryset = Memo.objects.all().order_by('-update_time')
        else:
            self.queryset = Memo.objects.all().order_by('-update_time')
        return super(MemoLV, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(MemoLV, self).get_context_data(**kwargs)
        context['login_user_name'] = self.request.user
        return context


def signup(requset):
    if requset.method == 'POST':
        form = UserForm(requset.POST)
        if form.is_valid():
            new_user = User.objects.create_user(**form.cleaned_data)
            auth_login(requset, new_user)
            return redirect('memo:index')
    else:
        form = UserForm

    return render(requset, 'user/signup.html', {'form': form})

def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        print(request.POST['username'])
        print(request.POST['password'])
        print(request.POST)
        print(form.errors)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                auth_login(request, user)
                return redirect('memo:index')

        messages.warning(request, '로그인 실패. 다시 시도 해보세요.')
        return HttpResponseRedirect('/')

    else:
        form = LoginForm()

    return render(request, 'user/login.html', {'form':form})

@login_required
def logout(request):
    if request.user.is_authenticated:
        user = User.objects.get(username=request.user.get_username())
        auth_logout(request)

        messages.info(request, '로그아웃 되셨습니다.')
        return HttpResponseRedirect('/')

    else:
        messages.warning(request, '로그인한 유저만 가능합니다.')
        return HttpResponseRedirect('/')


def make(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = MemoForm(request.POST)
            if form.is_valid():
                memo = form.save(commit=False)
                memo.user_name = User.objects.get(username = request.user.get_username())
                memo.save_memo()
                return redirect('memo:index')
        else:
            form = MemoForm()
        return render(request, 'memo/make_memo.html' , {'form':form})
    else:

        messages.warning(request, '로그인한 유저만 메시지를 남길수 있습니다.')
        return HttpResponseRedirect('/')

def delete(request, pk):
    memo = Memo.objects.get(pk=pk)
    user = User.objects.get(username=request.user.get_username())

    if memo.user_name == user:
        memo.delete()
        messages.info(request, '성공적으로 삭제되었습니다.')
        return HttpResponseRedirect('/')
    else:
        return render(request, 'memo/warning.html')

def modify(request, pk):
    memo = Memo.objects.get(pk=pk)

    if request.method == 'POST':
        user = User.objects.get(username=request.user.get_username())
        form = MemoForm(request.POST, instance=memo)
        if user == memo.user_name:
            if form.is_valid():
                form.save()
                return redirect('memo:index')
        else:
            return redirect(request,'/memo/warning.html')
    else:
        form = MemoForm(instance=memo)

    return render(request, 'memo/modify_memo.html', {'memo':memo, 'form':form})


def like(request, pk):
    if request.user.is_authenticated:
        memo = Memo.objects.get(pk=pk)
        user = User.objects.get(username=request.user.get_username())

        if memo.likes.filter(id=user.id).exists():
            memo.likes.remove(user)
        else:
            memo.likes.add(user)
        return redirect('memo:index')

    else:
        messages.warning(request, '로그인한 유저만 좋아요할수 있습니다.')
        return HttpResponseRedirect('/')

templates/base_layout/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- 위 3개의 메타 태그는 *반드시* head 태그의 처음에 와야합니다; 어떤 다른 콘텐츠들은 반드시 이 태그들 *다음에* 와야 합니다 -->
        <title> 메모 프로젝트</title>
        <!-- 부트스트랩 -->
        <link href="{% static 'css/webarch.css' %}" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
        <!-- 부가적인 테마 -->
        <![endif]-->
    </head>
    <body class="horizontal-menu">
        <!-- BEGIN HEADER -->
        {% include 'base_layout/top_nav.html' %}
        <!-- END HEADER -->
        <!-- BEGIN CONTAINER -->
        <div class="page-container row-fluid">
            <div class="page-content">
                <div class="content">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="row  m-r-10 m-l-10">
                                <div class="alert {% if message.tags %} alert-{{ message.tags }} {% endif %} ">
                                    <button class="close" data-dismiss="alert"></button>
                                    {{ message }}
                                </div>
                            </div>
                        {% endfor %}
                    {% endif %}

                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
        <script src="//code.jquery.com/jquery.min.js"></script>
        <script src="{% static 'js/webarch.js' %}" type="text/javascript"></script>
        <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>
        <script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.6.2/modernizr.min.js"></script>
        <script src="http:////cdnjs.cloudflare.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script src="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.1/js/bootstrap.min.js"></script>
    </body>
</html>

templates/base_layout/top_nav.html
<div class="header">
      <!-- BEGIN TOP NAVIGATION BAR -->
      <div class="navbar-inner">

        <!-- END RESPONSIVE MENU TOGGLER -->
        <div class="header-quick-nav">
          <!-- BEGIN TOP NAVIGATION MENU -->
          <div class="pull-left">

            <ul class="nav quick-section">
              <li class="quicklinks  m-r-10">
                <a data-toggle="dropdown" class="dropdown-toggle  pull-right " href="#" id="user-options">
                  <i class="material-icons">
                    메모
                  </i>
                </a>
              <ul class="dropdown-menu  pull-left" role="menu" aria-labelledby="user-options">

                      <li>
                        <a href="{% url 'memo:index' %}">메인화면</a>
                      </li>
                      <li>
                        <a href="{% url 'memo:make' %}">메모남기기</a>
                      </li>
                </ul>
              </li>
            </ul>
          </div>
          <div class="pull-right">
            <ul class="nav quick-section ">
              <li class="quicklinks">
                <a data-toggle="dropdown" class="dropdown-toggle  pull-right " href="#" id="user-options">
                  <i class="material-icons">
                  {% if user.is_authenticated %}
                        {{ user.username }} 오신것을 환영합니다.
                  {% else %}
                      로그인
                  {% endif %}
                  </i>
                </a>
                <ul class="dropdown-menu  pull-right" role="menu" aria-labelledby="user-options">
                  {% if user.is_anonymous %}
                      <li>
                        <a href="{% url 'memo:join' %}">회원가입</a>
                      </li>
                      <li>
                        <a href="{% url 'memo:login' %}">로그인</a>
                      </li>
                  {% else %}
                     <li>
                        <a href="{% url 'memo:logout' %}">Log Out</a>
                      </li>
                  {% endif %}
                </ul>
              </li>

            </ul>
          </div>
          <!-- END CHAT TOGGLER -->
        </div>
        <!-- END TOP NAVIGATION MENU -->
      </div>
      <!-- END TOP NAVIGATION BAR -->
    </div>

templates/memo/make_memo.html
{% extends 'base_layout/layout.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-12">
            <div class="grid simple">
                <div class="grid-title no-border">
                    <h4>Make <span class="semi-bold">Memo</span></h4>
                </div>
                <div class="grid-body no-border">
                    <br>
                    <div class="row">
                        <div class="col-md-8 col-sm-8 col-xs-8">
                            <div class="form-group">
                                <label class="form-label">Title</label>
                                <span class="help">e.g. "안녕하세요"</span>
                                <div class="controls">
                                    {{ form.title }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="form-label">내용</label>
                                <span class="help">e.g. "간단한 메모입니다."</span>
                                <div class="controls">
                                    {{ form.content }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">저장하기</button>
        </div>
    </div>
</form>
{% endblock %}

templates/memo/memo_list.html
{% extends 'base_layout/layout.html' %}
{% block content %}
{% load custom_tags %}
<div class="row col-md-12 m-b-10 m-l-10">
    정렬하기
    <div class="btn-group">
        <a class="btn dropdown-toggle btn-demo-space" data-toggle="dropdown" href="#"> 정렬 <span class="caret"></span> </a>
        <ul class="dropdown-menu">
            <li><a href="/?orderby=like">좋아요</a></li>
            {% if user.is_authenticated %}
            <li><a href="/?orderby=mypost">내가 쓴 메모</a></li>
            {% endif %}
            <li><a href="/?orderby=update">날짜순</a></li>
        </ul>
    </div>
</div>
<div class="row">
    {% for num in '1230' %}
        <div class="col-md-3 col-sm-6">
            {% for memo in memo_list %}
                {% with result=forloop.counter|modulo:4 %}
                    {% if num|to_int == result %}
                <div class="row">
                    <div class="col-md-12 m-b-10">
                        <div class="widget-item ">
                            <div class="tiles green " style="max-height:72px">
                                <div class="tiles-body" style="padding: 1px 18px 15px 24px;">
                                    <h3> {{ memo.title }}
                                    </h3>
                                </div>
                            </div>
                            <div class="tiles white ">
                                <div class="tiles-body">
                                    <div class="row">
                                        <div class="p-l-15 p-t-10 p-r-20">
                                            <p>{{ memo.content|linebreaksbr }}</p>
                                            <div class="post p-t-10 p-b-10">
                                                <ul class="action-bar no-margin p-b-20 ">
                                                    <li>
                                                        <a href="{% url 'memo:like' pk=memo.pk %}"  class="text-error bold">
                                                        {% with like_user=memo.likes.all %}
                                                        {% if login_user_name in like_user %}
                                                        <i class="fa fa-heart  m-r-10"></i>
                                                        {% else %}
                                                        <i class="fa fa-heart-o  m-r-10"></i>
                                                        {% endif %}
                                                        {{ memo.total_like }}
                                                        {% endwith %}
                                                        </a>
                                                    </li>
                                                </ul>
                                                <span class="bold text-black small-text pull-right">{{ memo.update_time | date:"Y-m-d H:m:s" }}</span>
                                                <div class="clearfix"></div>
                                            </div>
                                            {% if login_user_name == memo.user_name %}
                                            <a href="{% url 'memo:modify' pk=memo.pk %}">수정</a>
                                            <a href="{% url 'memo:delete' pk=memo.pk %}" onclick="return confirm('정말 삭제하시겠습니까?')">삭제</a>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
                {% endwith %}
            {% endfor %}
        </div>
    {% endfor %}
</div>
{% endblock content %}
{% for memo in memo_list %}
{{ forloop.parentloop.counter }}
<div class="col-md-4 col-sm-6"></div>
{% endfor %}

templates/memo/modify_memo.html
{% extends 'base_layout/layout.html' %}

{% block content %}
    <form method="post">
    {% csrf_token %}
    <div class="row">
            <div class="col-md-12">
              <div class="grid simple">
                <div class="grid-title no-border">
                  <h4>Make <span class="semi-bold">Memo</span></h4>
                </div>
                <div class="grid-body no-border">
                  <br>
                  <div class="row">
                    <div class="col-md-8 col-sm-8 col-xs-8">
                      <div class="form-group">
                        <label class="form-label">Title</label>
                        <span class="help">e.g. "안녕하세요"</span>
                        <div class="controls">
                          {{ form.title }}
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="form-label">내용</label>
                        <span class="help">e.g. "간단한 메모입니다."</span>
                        <div class="controls">
                            {{ form.content }}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
                <button type="submit" class="btn btn-primary">수정하기</button>
            </div>
          </div>
    </form>
{% endblock %}

templates/memo/warning.html
{% extends 'base_layout/layout.html' %}

{% block content %}
    본인만 수정 / 삭제할수 있습니다.
{% endblock %}

templates/user/login.html
{% extends 'base_layout/layout.html' %}

{% block content %}

    <div class="row login-container column-seperation">
        <div class="col-md-5 col-md-offset-1">
          <h2>
        로그인하여 메모를 남기세요.
      </h2>
          <p>
            로그인하여 간단하게 메모를 남기세요.
            <br>
            <a href="{% url 'memo:join' %}">Sign up Now!</a> 아이디가 없으신분은 옆에 링크를 통해 회원가입을 해주세요
          </p>
          <br>
        </div>
        <div class="col-md-5">
          <br>
          <form method="post" action="{% url 'memo:login' %}" class="sign-in-form">
  {%csrf_token%}
  <h2 class="sub-title"> 로그인 </h2>
  {% if form.errors %}
  <p>Your username and password didn't match. Please try again.</p>
  {% endif %}
  {% if next %}
      {% if user.is_authenticated %}
      <p>Your account doesn't have access to this page. To proceed,
      please login with an account that has access.</p>
      {% else %}
      <p>Please login to see this page.</p>
      {% endif %}
  {% endif %}
  <div class="form-group">
    <label for="{{ form.username.id_for_label }}">닉네임</label>
    <input class="form-control" id="{{ form.username.id_for_label }}" maxlength="15" name="{{ form.username.html_name }}" type="text" />
  </div>
  <div class="form-group">
    <label for="{{ form.password.id_for_label }}">패스워드</label>
    <input class="form-control" id="{{ form.password.id_for_label }}" maxlength="120" name="{{ form.password.html_name }}" type="password" />
  </div>
  <input type="submit" class="save btn btn-success" value="로그인">
  <a href="{% url 'memo:index' %}">
    <button type="button" class="btn btn-danger">취소</button>
  </a>
</form>

          </form>

        </div>
      </div>

{% endblock %}

templates/user/signup.html
{% extends 'base_layout/layout.html' %}

{% block content %}
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">submit</button>
    </form>
{% endblock %}